UAOLD="Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)"
UANEW="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

post_install() {
	post_upgrade
}

post_upgrade() {
	echo "Replacing User-Agent in http.lua library"
	sed -i -e "s|$UAOLD|$UANEW|g" /usr/share/nmap/nselib/http.lua
}

post_remove() {
	echo "Reverting replaced User-Agent in http.lua library"
	sed -i -e "s|$UANEW|$UAOLD|g" /usr/share/nmap/nselib/http.lua
}
